- name: 'Find existing jails for {{ app_name }}'
  shell: ezjail-admin list | awk '/{{ app_name }}/ { print $4 }'
  register: app_jail_dirs

- name: 'Generate id for new {{ app_name }} jail'
  set_fact:
    app_jail_id: >-
      {{ "%05d" %
      (((app_jail_dirs.stdout_lines | sort | last | default('-0')).split('-')
      | last | int) + 1)
      }}


- name: 'Read the counter file'
  command: 'cat /var/adhokku/counter'
  register: counter_read

- name: 'Set the counter variable'
  set_fact:
    counter: '{{ (counter_read.stdout | int) + 10 }}'


- name: 'Generate name and IP address for new {{ app_name }} jail'
  set_fact:
    app_jail_name: '{{ app_name }}-{{ app_jail_id }}'
    app_jail_address: >-
      10.{{ ((counter | int) // 65536) % 256
      }}.{{ ((counter | int) //   256) % 256
      }}.{{  (counter | int)           % 256 }}

- name: 'Write incremented counter to counter file'
  copy:
    content: "{{ (counter_read.stdout | int) + 1 }}\n"
    dest: /var/adhokku/counter

- name: 'Create new {{ app_name }} jail'
  command: >-
    ezjail-admin create '{{ app_jail_name }}' 'lo1|{{ app_jail_address }}'

- name: 'Start new {{ app_name }} jail'
  command: ezjail-admin start '{{ app_jail_name }}'

- name: 'Write /etc/hosts for new {{ app_name }} jail'
  copy:
    content: '{{ app_jail_address }} localhost'
    dest: '/usr/jails/{{ app_jail_name }}/etc/hosts'

- name: 'Write resolv.conf for new {{ app_name }} jail'
  copy:
    content: "nameserver 8.8.8.8\nnameserver 8.8.4.4"
    dest: '/usr/jails/{{ app_jail_name }}/etc/resolv.conf'


# Needed to enable NAT for the new jail.
- include: start-pf.yml


- include: deploy-git.yml
  when: deploy_via == 'git'


- name: 'Run Jailfile'
  shell: >-
    echo 'sh -c "PORT={{ app_port }} . /app/Jailfile"'
    | ezjail-admin console '{{ app_jail_name }}'


- name: 'Write Nginx config for {{ app_name }}'
  template:
    owner: root
    group: wheel
    mode: 0644
    src: templates/app.conf.j2
    dest: /usr/local/etc/nginx/sites-enabled/{{ app_name }}.conf

# Reload Nginx configuration to direct traffic to the new jail before we shut
# down the previous one.
- include: reconfigure-nginx.yml


- name: 'Stop other jails for {{ app_name }}'
  shell: >-
    ezjail-admin stop '{{ item | basename }}'
    && ezjail-admin config -r norun '{{ item | basename }}'
  with_items: '{{ app_jail_dirs.stdout_lines }}'

- name: 'Delete other jails for {{ app_name }}'
  shell: ezjail-admin delete -w '{{ item | basename }}'
  with_items: '{{ app_jail_dirs.stdout_lines }}'
  when: delete_old_jails == True
