- name: 'Find existing jails for {{ app_name }}'
  find:
    file_type: directory
    paths: /usr/jails
    patterns: '{{ app_name }}*'
  register: app_jail_dirs

- name: 'Generate id for new {{ app_name }} jail'
  set_fact:
    app_jail_id: >-
      {{ "%05d" %
      (((app_jail_dirs.files
      | map(attribute='path') | sort | last | default('-0')).split('-')
      | last | int) + 1)
      }}


- name: 'Read the counter file'
  command: 'cat /var/adhokku/counter'
  register: counter_read

- name: 'Set the counter variable'
  set_fact:
    counter: '{{ (counter_read.stdout | int) + 10 }}'


- name: 'Generate name and IP address for new {{ app_name }} jail'
  set_fact:
    app_jail_name: '{{ app_name }}-{{ app_jail_id }}'
    app_jail_address: >-
      10.{{ ((counter | int) // 65536) % 256
      }}.{{ ((counter | int) //   256) % 256
      }}.{{  (counter | int)           % 256 }}

- name: 'Write incremented counter to counter file'
  copy:
    content: "{{ (counter_read.stdout | int) + 1 }}\n"
    dest: /var/adhokku/counter

- name: 'Create new {{ app_name }} jail'
  command: ezjail-admin create '{{ app_jail_name }}' 'lo1|{{ app_jail_address }}'

- name: 'Start new {{ app_name }} jail'
  command: ezjail-admin start '{{ app_jail_name }}'

- name: 'Write /etc/hosts for new {{ app_name }} jail'
  shell: echo 'echo "{{ app_jail_address }} localhost" > /etc/hosts' | ezjail-admin console '{{ app_jail_name }}'

- name: 'Write resolv.conf for new {{ app_name }} jail'
  shell: echo 'echo "nameserver 8.8.8.8" > /etc/resolv.conf' | ezjail-admin console '{{ app_jail_name }}'


# Needed to enable NAT for the new jail.
- include: start-pf.yml


- include: deploy-git.yml
  when: deploy_via == 'git'


- name: 'Run Jailfile'
  command: ezjail-admin console -e 'sh /app/Jailfile' '{{ app_jail_name }}'


- name: 'Write Nginx config for {{ app_name }}'
  template:
    owner: root
    group: wheel
    mode: 0644
    src: templates/app.conf.j2
    dest: /usr/local/etc/nginx/sites-enabled/{{ app_name }}.conf

# Reload Nginx configuration to direct traffic to the new jail before we shut down the previous one.
- include: reconfigure-nginx.yml


- name: 'Stop other jails for {{ app_name }}'
  shell: ezjail-admin stop '{{ item.path | basename }}'
  with_items: '{{ app_jail_dirs.files }}'
