- name: 'Install ezjail'
  pkgng:
    name: ezjail
    state: present

- name: '(rc.conf) Start ezjail on boot'
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^ezjail_enable
    line: 'ezjail_enable="YES"'


- name: '(rc.conf) Clone loopback interface lo1'
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^cloned_interfaces
    line: 'cloned_interfaces="lo1"'

- name: '(rc.conf) Set lo1 IP address and mask'
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^ifconfig_lo1
    line: 'ifconfig_lo1="inet 10.0.0.1 netmask 255.255.255.0"'


- include: pf.yml


- name: 'Start cloned interface'
  command: service netif cloneup

- name: 'Check if base jail exists'
  stat: path=/usr/jails/basejail
  register: basejail_dir

- name: 'Create base jail'
  command: ezjail-admin install
  when: basejail_dir.stat.exists == False

# TODO: figure out non-interactive basejail updates
