- name: 'install ezjail'
  pkgng:
    name: ezjail
    state: present

- name: 'auto start ezjail'
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^ezjail_enable
    line: 'ezjail_enable="YES"'


- name: 'clone loopback lo1'
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^cloned_interfaces
    line: 'cloned_interfaces="lo1"'

- name: 'set lo1 IP address and mask'
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^ifconfig_lo1
    line: 'ifconfig_lo1="inet 10.0.0.1 netmask 255.255.255.0"'


- include: pf.yml


- name: 'start cloned interfaces'
  command: service netif cloneup

- name: 'check if basejail exists'
  stat: path=/usr/jails/basejail
  register: basejail_dir

- name: 'create basejail'
  command: ezjail-admin install -p
  when: basejail_dir.stat.exists == False

# TODO: figure out non-interactive basejail updates
