- name: '(rc.conf) Enable PF'
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^pf_enable
    line: 'pf_enable="YES"'

- name: "(rc.conf) Specify PF rules file"
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^pf_rules
    line: 'pf_rules="/etc/pf.conf"'

- name: 'Write pf.conf'
  template:
    owner: root
    group: wheel
    mode: 0644
    src: templates/pf.conf.j2
    dest: /etc/pf.conf
