- name: 'Install Git'
  pkgng:
    name: git
    state: present


- name: 'Create user {{ deployer_username }}'
  user:
    name: '{{ deployer_username }}'
    state: present

- name: "Authorize current SSH user's key for remote user {{ deployer_username }}"
  authorized_key:
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
    state: present
    user: '{{ deployer_username }}'
