- name: 'Install Nginx'
  pkgng:
    name: nginx
    state: present

- name: 'Create sites-enabled directory for Nginx'
  file:
    path: /usr/local/etc/nginx/sites-enabled
    owner: root
    group: wheel
    mode: 0755
    state: directory

- name: 'Write nginx.conf'
  template:
    owner: root
    group: wheel
    mode: 0644
    src: templates/nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf

- include: reconfigure-nginx.yml

- name: '(rc.conf) Start Nginx on boot'
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^nginx_enable
    line: 'nginx_enable="YES"'
